<?php defined('BASEPATH') OR exit('No direct script access allowed');

$config['full_tag_open'] = '<ul class="pagination">';
$config['full_close_open'] = '</ul>';
$config['first_link'] = '&laquo; First';
$config['last_link'] = 'Last &raquo;';
$config['next_link'] = 'Next &rsaquo;';
$config['prev_link'] = '&lsaquo; Prev';
$config['first_tag_open'] = '<li>';
$config['first_tag_close'] = '</li>';
$config['last_tag_open'] = '<li>';
$config['last_tag_close'] = '</li>';
$config['next_tag_open'] = '<li>';
$config['next_tag_close'] = '</li>';
$config['prev_tag_open'] = '<li>';
$config['prev_tag_close'] = '</li>';
$config['cur_tag_open'] = '<li class="active"><a>';
$config['cur_tag_close'] = '</a></li>';
$config['num_tag_open'] = '<li>';
$config['num_tag_close'] = '</li>';
$config['use_page_numbers'] = FALSE;
